// System role → permission grants, transcribed verbatim from the "Rollen ×
// Berechtigungen Matrix" in docs/04_ROLES_PERMISSIONS_MATRIX.md.
//
// Permissions marked `*` or `**` in that matrix (organisationsweit
// konfigurierbar bzw. kontextabhängig/Delegation) are deliberately NOT
// included in PROJECT_LEAD's default grant below — masterprompt.md Kap. 0
// requires a conservative default for open points, and the doc's own
// footnote says QM decides by default. Granting them org-wide is a Phase 2+
// configuration action (role.manage), not a hardcoded default.

export const SYSTEM_ROLES = {
  ADMIN: {
    name: 'Administrator',
    permissions: [
      'organization.manage',
      'site.manage',
      'user.manage',
      'role.manage',
      'qualification.manage',
      'delegation.create',
      'project.view',
      'document.view',
      'production_order.view',
      'work_step.view',
      'ncr.view',
      'audit.view',
      'report.generate',
      'dossier.export',
    ],
  },
  QUALITY_MANAGER: {
    name: 'Qualitätsmanager',
    permissions: [
      'qualification.manage',
      'delegation.create',
      'project.view',
      'document.review',
      'document.approve',
      'document.release',
      'document.withdraw',
      'document.view',
      'production_plan.review',
      'production_plan.approve',
      'production_order.view',
      'work_step.view',
      'completion_submission.validate',
      'second_approval.decide',
      'skip_request.decide',
      'ncr.create',
      'ncr.assess',
      'ncr.disposition',
      'ncr.view',
      'rework.create',
      'production_hold.create',
      'production_hold.release',
      'equipment.manage',
      'calibration.manage',
      'audit.view',
      'report.generate',
      'export.create',
      'dossier.export',
    ],
  },
  PROJECT_LEAD: {
    name: 'Projektleiter / Arbeitsvorbereitung',
    permissions: [
      'delegation.create',
      'project.create',
      'project.view',
      'project.update',
      'document.upload',
      'document.revise',
      'document.review',
      'document.view',
      'production_plan.create',
      'production_plan.update',
      'work_step_definition.create',
      'work_step_definition.update',
      'production_order.view',
      'work_step.view',
      'ncr.create',
      'ncr.view',
      'audit.view',
      'report.generate',
      'export.create',
      'dossier.export',
    ],
  },
  PRODUCTION_MANAGER: {
    name: 'Produktionsleiter',
    permissions: [
      'delegation.create',
      'project.view',
      'production_order.create',
      'production_order.schedule',
      'production_order.assign',
      'production_order.view',
      'work_step.view',
      'ncr.create',
      'ncr.view',
      'production_hold.create',
      'audit.view',
      'report.generate',
    ],
  },
  WORKER: {
    name: 'Produktionsmitarbeiter',
    permissions: [
      'project.view',
      'document.view',
      'production_order.view',
      'work_step.execute',
      'work_step.pause',
      'work_step.view',
      'work_step.complete_locally',
      'skip_request.create',
      'ncr.create',
      'ncr.view',
    ],
  },
  INSPECTOR: {
    name: 'Prüfer',
    permissions: [
      'project.view',
      'document.view',
      'production_order.view',
      'work_step.view',
      'second_approval.decide',
      'ncr.create',
      'ncr.view',
      'reinspection.execute',
    ],
  },
  AUDITOR: {
    name: 'Auditor / Read-only',
    permissions: [
      'project.view',
      'document.view',
      'production_order.view',
      'work_step.view',
      'ncr.view',
      'audit.view',
      'report.generate',
      'export.create',
      'dossier.export',
    ],
  },
} as const;

export type SystemRoleCode = keyof typeof SYSTEM_ROLES;
